// 1. Укажите имя кэша и версию. Меняйте версию при каждом обновлении файлов!
const CACHE_NAME = "pwa-prof-v1";

// 2. Перечислите ВСЕ файлы, которые должны работать офлайн.
// Пути должны быть относительными от корня сайта (с учётом имени репозитория).
const ASSETS = [
  "/",
  "/aig.html",
  "/algorithm.html",
  "/atlas_derma.html",
  "/calc_amp.html",
  "/calc_burn.html",
  "/calc_burn_baby.html",
  "/calc_dopamin.html",
  "/calc_glasgo.html",
  "/calc_ls.html",
  "/calc_mass.html",
  "/css/app.css",
  "/css/app.old.css",
  "/css/framework7.material.colors.min.css",
  "/css/framework7.material.min.css",
  "/css/index.css",
  "/data/aig/PrilAG_033.html",
  "/data/aig/PrilAG_034.html",
  "/data/aig/PrilAG_035.html",
  "/data/aig/PrilAG_036.html",
  "/data/aig/PrilAG_037.html",
  "/data/aig/PrilAG_038.html",
  "/data/aig/PrilAG_039.html",
  "/data/aig/PrilAG_040.html",
  "/data/aig/PrilAG_041.html",
  "/data/aig/PrilAG_042.html",
  "/data/aig/PrilAG_043.html",
  "/data/aig/PrilAG_044.html",
  "/data/aig/PrilAG_045.html",
  "/data/aig/PrilAG_046.html",
  "/data/aig/PrilAG_047.html",
  "/data/aig/PrilAG_048.html",
  "/data/aig/PrilAG_049.html",
  "/data/aig/PrilAG_050.html",
  "/data/aig/PrilAG_051.html",
  "/data/aig/PrilAG_052.html",
  "/data/aig/PrilAG_053.html",
  "/data/aig/PrilAG_054.html",
  "/data/aig/PrilAG_055.html",
  "/data/aig/PrilAG_056.html",
  "/data/aig/PrilAG_057.html",
  "/data/aig/PrilAG_058.html",
  "/data/aig/PrilAG_059.html",
  "/data/aig/PrilAG_060.html",
  "/data/aig/PrilAG_061.html",
  "/data/aig/PrilAG_062.html",
  "/data/aig/PrilAG_063.html",
  "/data/aig/PrilAG_064.html",
  "/data/aig/PrilAG_065.html",
  "/data/aig/PrilAG_066.html",
  "/data/aig/PrilAG_067.html",
  "/data/aig/PrilAG_068.html",
  "/data/aig/PrilAG_069.html",
  "/data/aig/PrilAG_070.html",
  "/data/aig/PrilAG_071.html",
  "/data/aig/PrilAG_072.html",
  "/data/aig/PrilAG_073.html",
  "/data/aig/PrilAG_074.html",
  "/data/aig/PrilAG_075.html",
  "/data/aig/PrilAG_076.html",
  "/data/aig/PrilAG_077.html",
  "/data/aig/PrilAG_078.html",
  "/data/aig/PrilAG_079.html",
  "/data/aig/PrilAG_080.html",
  "/data/aig/PrilAG_081.html",
  "/data/aig/PrilAG_082.html",
  "/data/aig/PrilAG_083.html",
  "/data/aig/PrilAG_084.html",
  "/data/aig/PrilAG_085.html",
  "/data/aig/PrilAG_086.html",
  "/data/aig/PrilAG_087.html",
  "/data/aig/PrilAG_088.html",
  "/data/aig/PrilAG_089.html",
  "/data/aig/PrilAG_090.html",
  "/data/aig/PrilAG_091.html",
  "/data/aig/PrilAG_092.html",
  "/data/aig/PrilAG_093.html",
  "/data/aig/PrilAG_094.html",
  "/data/aig/PrilAG_095.html",
  "/data/aig/PrilAG_096.html",
  "/data/aig/PrilAG_097.html",
  "/data/aig/PrilAG_098.html",
  "/data/aig/PrilAG_099.html",
  "/data/aig/PrilAG_100.html",
  "/data/aig/PrilAG_101.html",
  "/data/aig/PrilAG_102.html",
  "/data/aig/PrilAG_103.html",
  "/data/aig/PrilAG_104.html",
  "/data/aig/PrilAG_105.html",
  "/data/aig/PrilAG_106.html",
  "/data/aig/PrilAG_107.html",
  "/data/aig/PrilAG_108.html",
  "/data/aig/PrilAG_109.html",
  "/data/aig/PrilAG_110.html",
  "/data/aig/PrilAG_111.html",
  "/data/aig/PrilAG_112.html",
  "/data/aig/PrilAG_113.html",
  "/data/aig/PrilAG_114.html",
  "/data/aig/PrilAG_115.html",
  "/data/aig/PrilAG_116.html",
  "/data/aig/PrilAG_117.html",
  "/data/aig/PrilAG_118.html",
  "/data/aig/PrilAG_119.html",
  "/data/aig/PrilAG_120.html",
  "/data/aig/PrilAG_121.html",
  "/data/aig/PrilAG_122.html",
  "/data/aig/PrilAG_123.html",
  "/data/aig/PrilAG_124.html",
  "/data/aig/PrilAG_125.html",
  "/data/aig/PrilAG_126.html",
  "/data/aig/PrilAG_127.html",
  "/data/aig/PrilAG_128.html",
  "/data/aig/PrilAG_129.html",
  "/data/aig/PrilAG_130.html",
  "/data/aig/PrilAG_131.html",
  "/data/aig/PrilAG_132.html",
  "/data/aig/PrilAG_133.html",
  "/data/aig/PrilAG_134.html",
  "/data/aig/PrilAG_135.html",
  "/data/aig/PrilAG_136.html",
  "/data/aig/PrilAG_137.html",
  "/data/aig/PrilAG_138.html",
  "/data/aig/PrilAG_139.html",
  "/data/aig/PrilAG_140.html",
  "/data/aig/PrilAG_141.html",
  "/data/aig/PrilAG_142.html",
  "/data/aig/PrilAG_143.html",
  "/data/aig/PrilAG_144.html",
  "/data/aig/PrilAG_145.html",
  "/data/aig/PrilAG_146.html",
  "/data/aig/PrilAG_147.html",
  "/data/aig/PrilAG_148.html",
  "/data/aig/PrilAG_149.html",
  "/data/aig/PrilAG_150.html",
  "/data/aig/PrilAG_151.html",
  "/data/aig/PrilAG_152.html",
  "/data/aig/PrilAG_153.html",
  "/data/aig/PrilAG_154.html",
  "/data/aig/PrilAG_155.html",
  "/data/aig/PrilAG_156.html",
  "/data/aig/PrilAG_157.html",
  "/data/aig/PrilAG_158.html",
  "/data/aig/PrilAG_159.html",
  "/data/aig/PrilAG_160.html",
  "/data/aig/PrilAG_161.html",
  "/data/aig/PrilAG_162.html",
  "/data/aig/PrilAG_163.html",
  "/data/aig/PrilAG_164.html",
  "/data/aig/PrilAG_165.html",
  "/data/aig/PrilAG_166.html",
  "/data/aig/PrilAG_167.html",
  "/data/aig/PrilAG_168.html",
  "/data/aig/PrilAG_169.html",
  "/data/aig/PrilAG_170.html",
  "/data/aig/PrilAG_171.html",
  "/data/aig/PrilAG_172.html",
  "/data/aig/PrilAG_173.html",
  "/data/aig/PrilAG_174.html",
  "/data/aig/PrilAG_175.html",
  "/data/aig/PrilAG_176.html",
  "/data/aig/PrilAG_177.html",
  "/data/algorithm/Algoritm_001.html",
  "/data/algorithm/Algoritm_002.html",
  "/data/algorithm/Algoritm_003.html",
  "/data/algorithm/Algoritm_004.html",
  "/data/algorithm/Algoritm_005.html",
  "/data/algorithm/Algoritm_006.html",
  "/data/algorithm/Algoritm_007.html",
  "/data/algorithm/Algoritm_008.html",
  "/data/algorithm/Algoritm_009.html",
  "/data/algorithm/Algoritm_010.html",
  "/data/algorithm/Algoritm_011.html",
  "/data/algorithm/Algoritm_012.html",
  "/data/algorithm/Algoritm_013.html",
  "/data/algorithm/Algoritm_014.html",
  "/data/algorithm/Algoritm_015.html",
  "/data/algorithm/Algoritm_016.html",
  "/data/algorithm/Algoritm_017.html",
  "/data/algorithm/Algoritm_018.html",
  "/data/algorithm/Algoritm_019.html",
  "/data/algorithm/Algoritm_020.html",
  "/data/algorithm/Algoritm_021.html",
  "/data/algorithm/Algoritm_022.html",
  "/data/algorithm/Algoritm_023.html",
  "/data/algorithm/Algoritm_024.html",
  "/data/algorithm/Algoritm_025.html",
  "/data/algorithm/Algoritm_026.html",
  "/data/algorithm/Algoritm_027.html",
  "/data/algorithm/Algoritm_028.html",
  "/data/algorithm/Algoritm_029.html",
  "/data/algorithm/Algoritm_030.html",
  "/data/algorithm/Algoritm_031.html",
  "/data/algorithm/Algoritm_032.html",
  "/data/algorithm/Algoritm_033.html",
  "/data/algorithm/Algoritm_034.html",
  "/data/algorithm/Algoritm_035.html",
  "/data/algorithm/Algoritm_036.html",
  "/data/algorithm/Algoritm_037.html",
  "/data/algorithm/Algoritm_038.html",
  "/data/algorithm/Algoritm_039.html",
  "/data/algorithm/Algoritm_040.html",
  "/data/algorithm/Algoritm_041.html",
  "/data/algorithm/Algoritm_042.html",
  "/data/algorithm/Algoritm_043.html",
  "/data/algorithm/Algoritm_044.html",
  "/data/algorithm/Algoritm_045.html",
  "/data/algorithm/Algoritm_046.html",
  "/data/algorithm/Algoritm_047.html",
  "/data/algorithm/Algoritm_048.html",
  "/data/algorithm/Algoritm_049.html",
  "/data/algorithm/Algoritm_050.html",
  "/data/algorithm/Algoritm_051.html",
  "/data/algorithm/Algoritm_052.html",
  "/data/algorithm/Algoritm_053.html",
  "/data/algorithm/Algoritm_054.html",
  "/data/algorithm/Algoritm_055.html",
  "/data/algorithm/Algoritm_056.html",
  "/data/algorithm/Algoritm_057.html",
  "/data/algorithm/Algoritm_058.html",
  "/data/algorithm/Algoritm_059.html",
  "/data/algorithm/Algoritm_060.html",
  "/data/algorithm/Algoritm_061.html",
  "/data/algorithm/Algoritm_062.html",
  "/data/algorithm/Algoritm_063.html",
  "/data/algorithm/Algoritm_064.html",
  "/data/algorithm/Algoritm_065.html",
  "/data/algorithm/Algoritm_066.html",
  "/data/algorithm/Algoritm_067.html",
  "/data/algorithm/Algoritm_068.html",
  "/data/algorithm/Algoritm_069.html",
  "/data/algorithm/Algoritm_070.html",
  "/data/algorithm/Algoritm_071.html",
  "/data/algorithm/Algoritm_072.html",
  "/data/algorithm/Algoritm_073.html",
  "/data/algorithm/Algoritm_074.html",
  "/data/algorithm/Algoritm_075.html",
  "/data/algorithm/Algoritm_076.html",
  "/data/algorithm/Algoritm_077.html",
  "/data/algorithm/Algoritm_078.html",
  "/data/algorithm/Algoritm_079.html",
  "/data/algorithm/Algoritm_080.html",
  "/data/algorithm/Algoritm_081.html",
  "/data/algorithm/Algoritm_082.html",
  "/data/algorithm/Algoritm_083.html",
  "/data/algorithm/Algoritm_084.html",
  "/data/algorithm/Algoritm_085.html",
  "/data/algorithm/Algoritm_086.html",
  "/data/algorithm/Algoritm_087.html",
  "/data/algorithm/Algoritm_088.html",
  "/data/algorithm/Algoritm_089.html",
  "/data/algorithm/Algoritm_090.html",
  "/data/algorithm/Algoritm_091.html",
  "/data/algorithm/Algoritm_092.html",
  "/data/algorithm/Algoritm_093.html",
  "/data/algorithm/Algoritm_094.html",
  "/data/algorithm/Algoritm_095.html",
  "/data/algorithm/Algoritm_096.html",
  "/data/algorithm/Algoritm_097.html",
  "/data/algorithm/Algoritm_098.html",
  "/data/algorithm/Algoritm_099.html",
  "/data/algorithm/Algoritm_100.html",
  "/data/algorithm/Algoritm_101.html",
  "/data/algorithm/Algoritm_102.html",
  "/data/algorithm/Algoritm_103.html",
  "/data/algorithm/Algoritm_104.html",
  "/data/algorithm/Algoritm_105.html",
  "/data/algorithm/Algoritm_106.html",
  "/data/algorithm/Algoritm_107.html",
  "/data/algorithm/Algoritm_108.html",
  "/data/algorithm/Algoritm_109.html",
  "/data/algorithm/Algoritm_110.html",
  "/data/algorithm/Algoritm_111.html",
  "/data/algorithm/Algoritm_112.html",
  "/data/algorithm/Algoritm_113.html",
  "/data/algorithm/Algoritm_114.html",
  "/data/algorithm/Algoritm_115.html",
  "/data/algorithm/Algoritm_116.html",
  "/data/algorithm/Algoritm_117.html",
  "/data/algorithm/Algoritm_118.html",
  "/data/algorithm/Algoritm_119.html",
  "/data/algorithm/Algoritm_120.html",
  "/data/algorithm/Algoritm_121.html",
  "/data/algorithm/Algoritm_122.html",
  "/data/algorithm/Algoritm_123.html",
  "/data/algorithm/Algoritm_124.html",
  "/data/algorithm/Algoritm_125.html",
  "/data/algorithm/Algoritm_126.html",
  "/data/algorithm/Algoritm_127.html",
  "/data/algorithm/Algoritm_128.html",
  "/data/algorithm/Algoritm_129.html",
  "/data/algorithm/Algoritm_130.html",
  "/data/algorithm/Algoritm_131.html",
  "/data/algorithm/Algoritm_132.html",
  "/data/algorithm/Algoritm_133.html",
  "/data/algorithm/Algoritm_134.html",
  "/data/algorithm/Algoritm_135.html",
  "/data/algorithm/Algoritm_136.html",
  "/data/algorithm/Algoritm_137.html",
  "/data/algorithm/Algoritm_138.html",
  "/data/algorithm/Algoritm_139.html",
  "/data/algorithm/Algoritm_140.html",
  "/data/algorithm/Algoritm_141.html",
  "/data/algorithm/Algoritm_142.html",
  "/data/algorithm/Algoritm_143.html",
  "/data/algorithm/Algoritm_144.html",
  "/data/algorithm/Algoritm_145.html",
  "/data/algorithm/Algoritm_146.html",
  "/data/algorithm/Algoritm_147.html",
  "/data/algorithm/Algoritm_148.html",
  "/data/algorithm/Algoritm_149.html",
  "/data/algorithm/Algoritm_150.html",
  "/data/algorithm/Algoritm_151.html",
  "/data/algorithm/Algoritm_152.html",
  "/data/algorithm/Algoritm_153.html",
  "/data/algorithm/Algoritm_154.html",
  "/data/algorithm/Algoritm_155.html",
  "/data/algorithm/Algoritm_156.html",
  "/data/algorithm/Algoritm_157.html",
  "/data/algorithm/Algoritm_158.html",
  "/data/algorithm/Algoritm_159.html",
  "/data/algorithm/Algoritm_160.html",
  "/data/algorithm/Algoritm_161.html",
  "/data/algorithm/Algoritm_162.html",
  "/data/algorithm/Algoritm_163.html",
  "/data/algorithm/Algoritm_164.html",
  "/data/algorithm/Algoritm_165.html",
  "/data/algorithm/Algoritm_166.html",
  "/data/algorithm/Algoritm_167.html",
  "/data/algorithm/Algoritm_168.html",
  "/data/algorithm/Algoritm_169.html",
  "/data/algorithm/Algoritm_170.html",
  "/data/algorithm/Algoritm_171.html",
  "/data/algorithm/Algoritm_172.html",
  "/data/algorithm/Algoritm_173.html",
  "/data/algorithm/Algoritm_174.html",
  "/data/algorithm/Algoritm_175.html",
  "/data/algorithm/Algoritm_176.html",
  "/data/algorithm/Algoritm_177.html",
  "/data/algorithm/Algoritm_178.html",
  "/data/algorithm/Algoritm_179.html",
  "/data/algorithm/Algoritm_180.html",
  "/data/algorithm/Algoritm_181.html",
  "/data/algorithm/Algoritm_182.html",
  "/data/algorithm/Algoritm_183.html",
  "/data/algorithm/Algoritm_184.html",
  "/data/algorithm/Algoritm_185.html",
  "/data/algorithm/Algoritm_186.html",
  "/data/algorithm/Algoritm_187.html",
  "/data/algorithm/Algoritm_188.html",
  "/data/algorithm/Algoritm_189.html",
  "/data/algorithm/Algoritm_190.html",
  "/data/algorithm/Algoritm_191.html",
  "/data/algorithm/Algoritm_192.html",
  "/data/algorithm/Algoritm_193.html",
  "/data/algorithm/Algoritm_194.html",
  "/data/algorithm/Algoritm_195.html",
  "/data/algorithm/Algoritm_196.html",
  "/data/algorithm/Algoritm_197.html",
  "/data/algorithm/Algoritm_198.html",
  "/data/algorithm/Algoritm_199.html",
  "/data/algorithm/Algoritm_200.html",
  "/data/algorithm/Algoritm_201.html",
  "/data/algorithm/Algoritm_202.html",
  "/data/algorithm/Algoritm_203.html",
  "/data/algorithm/Algoritm_204.html",
  "/data/algorithm/Algoritm_205.html",
  "/data/algorithm/Algoritm_206.html",
  "/data/algorithm/Algoritm_207.html",
  "/data/algorithm/Algoritm_208.html",
  "/data/algorithm/Algoritm_209.html",
  "/data/algorithm/Algoritm_210.html",
  "/data/algorithm/Algoritm_211.html",
  "/data/algorithm/Algoritm_212.html",
  "/data/algorithm/Algoritm_213.html",
  "/data/algorithm/Algoritm_214.html",
  "/data/algorithm/Algoritm_215.html",
  "/data/algorithm/Algoritm_216.html",
  "/data/algorithm/Algoritm_217.html",
  "/data/algorithm/Algoritm_218.html",
  "/data/algorithm/Algoritm_219.html",
  "/data/algorithm/Algoritm_220.html",
  "/data/algorithm/Algoritm_221.html",
  "/data/algorithm/Algoritm_222.html",
  "/data/algorithm/Algoritm_223.html",
  "/data/algorithm/Algoritm_224.html",
  "/data/algorithm/Algoritm_225.html",
  "/data/algorithm/Algoritm_226.html",
  "/data/algorithm/Algoritm_227.html",
  "/data/algorithm/Algoritm_228.html",
  "/data/algorithm/Algoritm_229.html",
  "/data/algorithm/Algoritm_230.html",
  "/data/algorithm/Algoritm_231.html",
  "/data/algorithm/Algoritm_232.html",
  "/data/algorithm/Algoritm_233.html",
  "/data/algorithm/Algoritm_234.html",
  "/data/algorithm/Algoritm_235.html",
  "/data/algorithm/Algoritm_236.html",
  "/data/algorithm/Algoritm_237.html",
  "/data/algorithm/Algoritm_238.html",
  "/data/algorithm/Algoritm_239.html",
  "/data/algorithm/Algoritm_240.html",
  "/data/algorithm/Algoritm_241.html",
  "/data/algorithm/Algoritm_242.html",
  "/data/algorithm/Algoritm_243.html",
  "/data/algorithm/Algoritm_244.html",
  "/data/algorithm/Algoritm_245.html",
  "/data/algorithm/Algoritm_246.html",
  "/data/algorithm/Algoritm_247.html",
  "/data/algorithm/Algoritm_248.html",
  "/data/algorithm/Algoritm_249.html",
  "/data/algorithm/Algoritm_250.html",
  "/data/algorithm/Algoritm_251.html",
  "/data/algorithm/Algoritm_252.html",
  "/data/algorithm/Algoritm_253.html",
  "/data/algorithm/Algoritm_254.html",
  "/data/algorithm/Algoritm_255.html",
  "/data/algorithm/Algoritm_256.html",
  "/data/algorithm/Algoritm_257.html",
  "/data/algorithm/Algoritm_258.html",
  "/data/algorithm/Algoritm_259.html",
  "/data/algorithm/Algoritm_260.html",
  "/data/algorithm/Algoritm_261.html",
  "/data/algorithm/Algoritm_262.html",
  "/data/algorithm/Algoritm_263.html",
  "/data/algorithm/Algoritm_264.html",
  "/data/algorithm/Algoritm_265.html",
  "/data/algorithm/Algoritm_266.html",
  "/data/algorithm/Algoritm_267.html",
  "/data/algorithm/Algoritm_268.html",
  "/data/algorithm/Algoritm_269.html",
  "/data/algorithm/Algoritm_270.html",
  "/data/algorithm/Algoritm_271.html",
  "/data/algorithm/Algoritm_272.html",
  "/data/algorithm/Algoritm_273.html",
  "/data/algorithm/Algoritm_274.html",
  "/data/algorithm/Algoritm_275.html",
  "/data/algorithm/Algoritm_276.html",
  "/data/algorithm/Algoritm_277.html",
  "/data/algorithm/Algoritm_278.html",
  "/data/algorithm/Algoritm_279.html",
  "/data/algorithm/Algoritm_280.html",
  "/data/algorithm/Algoritm_281.html",
  "/data/algorithm/Algoritm_282.html",
  "/data/algorithm/Algoritm_283.html",
  "/data/algorithm/Algoritm_284.html",
  "/data/algorithm/Algoritm_285.html",
  "/data/algorithm/Algoritm_286.html",
  "/data/algorithm/Algoritm_287.html",
  "/data/algorithm/Algoritm_288.html",
  "/data/algorithm/Algoritm_289.html",
  "/data/algorithm/Algoritm_290.html",
  "/data/algorithm/Algoritm_291.html",
  "/data/algorithm/Algoritm_292.html",
  "/data/algorithm/Algoritm_293.html",
  "/data/algorithm/Algoritm_294.html",
  "/data/algorithm/Algoritm_295.html",
  "/data/algorithm/Algoritm_296.html",
  "/data/algorithm/Algoritm_297.html",
  "/data/algorithm/Algoritm_298.html",
  "/data/algorithm/Algoritm_299.html",
  "/data/algorithm/Algoritm_300.html",
  "/data/algorithm/Algoritm_301.html",
  "/data/algorithm/Algoritm_302.html",
  "/data/algorithm/Algoritm_303.html",
  "/data/algorithm/Algoritm_304.html",
  "/data/algorithm/Algoritm_305.html",
  "/data/algorithm/Algoritm_306.html",
  "/data/algorithm/Algoritm_307.html",
  "/data/algorithm/Algoritm_308.html",
  "/data/algorithm/Algoritm_309.html",
  "/data/algorithm/Algoritm_310.html",
  "/data/algorithm/Algoritm_311.html",
  "/data/algorithm/Algoritm_312.html",
  "/data/algorithm/Algoritm_313.html",
  "/data/algorithm/Algoritm_314.html",
  "/data/algorithm/Algoritm_315.html",
  "/data/algorithm/Algoritm_316.html",
  "/data/algorithm/Algoritm_317.html",
  "/data/algorithm/Algoritm_318.html",
  "/data/algorithm/Algoritm_319.html",
  "/data/algorithm/Algoritm_320.html",
  "/data/algorithm/Algoritm_321.html",
  "/data/algorithm/Algoritm_322.html",
  "/data/algorithm/Algoritm_323.html",
  "/data/algorithm/Algoritm_324.html",
  "/data/algorithm/Algoritm_325.html",
  "/data/algorithm/Algoritm_327.html",
  "/data/algorithm/Algoritm_328.html",
  "/data/algorithm/Algoritm_329.html",
  "/data/algorithm/Algoritm_330.html",
  "/data/algorithm/Algoritm_331.html",
  "/data/algorithm/Algoritm_332.html",
  "/data/algorithm/Algoritm_333.html",
  "/data/algorithm/Algoritm_334.html",
  "/data/algorithm/Algoritm_335.html",
  "/data/algorithm/Algoritm_339.html",
  "/data/algorithm/Algoritm_340.html",
  "/data/algorithm/Algoritm_341.html",
  "/data/algorithm/Algoritm_342.html",
  "/data/algorithm/Algoritm_343.html",
  "/data/algorithm/Algoritm_344.html",
  "/data/algorithm/Algoritm_345.html",
  "/data/algorithm/Algoritm_346.html",
  "/data/algorithm/Algoritm_347.html",
  "/data/algorithm/Algoritm_348.html",
  "/data/algorithm/Algoritm_349.html",
  "/data/algorithm/Algoritm_350.html",
  "/data/algorithm/Algoritm_351.html",
  "/data/algorithm/Algoritm_352.html",
  "/data/algorithm/Algoritm_353.html",
  "/data/algorithm/Algoritm_354.html",
  "/data/algorithm/Algoritm_355.html",
  "/data/algorithm/Algoritm_356.html",
  "/data/algorithm/Algoritm_357.html",
  "/data/algorithm/Algoritm_358.html",
  "/data/algorithm/Algoritm_359.html",
  "/data/algorithm/Algoritm_360.html",
  "/data/algorithm/Algoritm_361.html",
  "/data/algorithm/Algoritm_362.html",
  "/data/algorithm/Algoritm_363.html",
  "/data/algorithm/Algoritm_364.html",
  "/data/algorithm/Algoritm_365.html",
  "/data/algorithm/Algoritm_366.html",
  "/data/algorithm/Algoritm_367.html",
  "/data/algorithm/Algoritm_368.html",
  "/data/algorithm/Algoritm_369.html",
  "/data/algorithm/Algoritm_370.html",
  "/data/algorithm/Algoritm_371.html",
  "/data/algorithm/Algoritm_372.html",
  "/data/algorithm/Algoritm_373.html",
  "/data/algorithm/Algoritm_374.html",
  "/data/algorithm/Algoritm_375.html",
  "/data/algorithm/Algoritm_376.html",
  "/data/algorithm/Algoritm_377.html",
  "/data/algorithm/Algoritm_378.html",
  "/data/algorithm/Algoritm_379.html",
  "/data/algorithm/Algoritm_380.html",
  "/data/algorithm/Algoritm_381.html",
  "/data/algorithm/Algoritm_382.html",
  "/data/algorithm/Algoritm_383.html",
  "/data/algorithm/Algoritm_384.html",
  "/data/algorithm/Algoritm_385.html",
  "/data/algorithm/Algoritm_386.html",
  "/data/algorithm/Algoritm_387.html",
  "/data/derma/Derma.files/image001.jpg",
  "/data/derma/Derma.files/image002.jpg",
  "/data/derma/Derma.files/image003.jpg",
  "/data/derma/Derma.files/image004.jpg",
  "/data/derma/Derma.files/image005.jpg",
  "/data/derma/Derma.files/image006.jpg",
  "/data/derma/Derma.files/image007.jpg",
  "/data/derma/Derma.files/image008.jpg",
  "/data/derma/Derma.files/image009.jpg",
  "/data/derma/Derma.files/image010.jpg",
  "/data/derma/Derma.files/image011.jpg",
  "/data/derma/Derma.files/image012.jpg",
  "/data/derma/Derma.files/image013.jpg",
  "/data/derma/Derma.files/image014.jpg",
  "/data/derma/Derma.files/image015.jpg",
  "/data/derma/Derma.files/image016.jpg",
  "/data/derma/Derma.files/image017.jpg",
  "/data/derma/Derma.files/image018.jpg",
  "/data/derma/Derma.files/image019.jpg",
  "/data/derma/Derma.files/image020.jpg",
  "/data/derma/Derma.files/image021.jpg",
  "/data/derma/Derma.files/image022.jpg",
  "/data/derma/Derma.files/image023.jpg",
  "/data/derma/Derma.files/image024.jpg",
  "/data/derma/Derma.files/image025.jpg",
  "/data/derma/Derma.files/image026.jpg",
  "/data/derma/Derma.files/image027.jpg",
  "/data/derma/Derma.files/image028.jpg",
  "/data/derma/Derma.files/image029.jpg",
  "/data/derma/Derma.files/image030.jpg",
  "/data/derma/Derma.files/image031.jpg",
  "/data/derma/Derma.files/image032.jpg",
  "/data/derma/Derma.files/image033.jpg",
  "/data/derma/Derma.files/image034.jpg",
  "/data/derma/Derma.files/image035.jpg",
  "/data/derma/Derma.files/image036.jpg",
  "/data/derma/Derma.files/image037.jpg",
  "/data/derma/Derma.files/image038.jpg",
  "/data/derma/Derma.files/image039.jpg",
  "/data/derma/Derma.files/image040.jpg",
  "/data/derma/Derma.files/image041.jpg",
  "/data/derma/Derma.files/image042.jpg",
  "/data/derma/Derma.files/image043.jpg",
  "/data/derma/Derma.files/image044.jpg",
  "/data/derma/Derma.files/image045.jpg",
  "/data/derma/Derma.files/image046.jpg",
  "/data/derma/Derma.files/image047.jpg",
  "/data/derma/Derma.files/image048.jpg",
  "/data/derma/Derma.files/image049.jpg",
  "/data/derma/Derma.files/image050.jpg",
  "/data/derma/Derma.files/image051.jpg",
  "/data/derma/Derma.files/image052.jpg",
  "/data/derma/Derma.files/image053.jpg",
  "/data/derma/Derma.files/image054.jpg",
  "/data/derma/Derma.files/image055.jpg",
  "/data/derma/Derma.files/image056.jpg",
  "/data/derma/Derma.files/image057.jpg",
  "/data/derma/Derma.files/image058.jpg",
  "/data/derma/Derma.files/image059.jpg",
  "/data/derma/Derma.files/image060.jpg",
  "/data/derma/Derma.files/image061.jpg",
  "/data/derma/Derma.files/image062.jpg",
  "/data/derma/Derma.files/image063.jpg",
  "/data/derma/Derma.files/image064.jpg",
  "/data/derma/Derma.files/image065.jpg",
  "/data/derma/Derma.files/image066.jpg",
  "/data/derma/Derma.files/image067.jpg",
  "/data/derma/Derma.files/image068.jpg",
  "/data/derma/Derma_001.html",
  "/data/derma/Derma_002.html",
  "/data/derma/Derma_003.html",
  "/data/derma/Derma_004.html",
  "/data/derma/Derma_005.html",
  "/data/derma/Derma_006.html",
  "/data/derma/Derma_007.html",
  "/data/derma/Derma_008.html",
  "/data/derma/Derma_009.html",
  "/data/derma/Derma_010.html",
  "/data/derma/Derma_011.html",
  "/data/derma/Derma_012.html",
  "/data/derma/Derma_013.html",
  "/data/derma/Derma_014.html",
  "/data/derma/Derma_015.html",
  "/data/derma/Derma_016.html",
  "/data/derma/Derma_017.html",
  "/data/derma/Derma_018.html",
  "/data/derma/Derma_019.html",
  "/data/derma/Derma_020.html",
  "/data/derma/Derma_021.html",
  "/data/derma/Derma_022.html",
  "/data/derma/Derma_023.html",
  "/data/ekg/Atlas_EKG_001.html",
  "/data/ekg/Atlas_EKG_002.html",
  "/data/ekg/Atlas_EKG_003.html",
  "/data/ekg/Atlas_EKG_004.html",
  "/data/ekg/Atlas_EKG_005.html",
  "/data/ekg/Atlas_EKG_006.html",
  "/data/ekg/Atlas_EKG_007.html",
  "/data/ekg/Atlas_EKG_008.html",
  "/data/ekg/Atlas_EKG_009.html",
  "/data/ekg/Atlas_EKG_010.html",
  "/data/ekg/Atlas_EKG_011.html",
  "/data/ekg/Atlas_EKG_012.html",
  "/data/ekg/Atlas_EKG_013.html",
  "/data/ekg/Atlas_EKG_014.html",
  "/data/ekg/Atlas_EKG_015.html",
  "/data/ekg/Atlas_EKG_016.html",
  "/data/ekg/Atlas_EKG_017.html",
  "/data/ekg/Atlas_EKG_018.html",
  "/data/ekg/Atlas_EKG_019.html",
  "/data/ekg/Atlas_EKG_020.html",
  "/data/ekg/Atlas_EKG_021.html",
  "/data/ekg/Atlas_EKG_022.html",
  "/data/ekg/Atlas_EKG_023.html",
  "/data/ekg/Atlas_EKG_024.html",
  "/data/ekg/Atlas_EKG_025.html",
  "/data/ekg/Atlas_EKG_026.html",
  "/data/ekg/Atlas_EKG_027.html",
  "/data/ekg/Atlas_EKG_028.html",
  "/data/ekg/EKG_026/image001.gif",
  "/data/ekg/EKG_026/image002.gif",
  "/data/ekg/EKG_026/image003.gif",
  "/data/ekg/EKG_026/image004.gif",
  "/data/ekg/EKG_026/image005.gif",
  "/data/ekg/EKG_026/image006.gif",
  "/data/ekg/EKG_026/image007.gif",
  "/data/ekg/EKG_026/image008.gif",
  "/data/ekg/EKG_027/image001.jpg",
  "/data/ekg/EKG_027/image002.jpg",
  "/data/ekg/EKG_027/image003.jpg",
  "/data/ekg/EKG_027/image004.jpg",
  "/data/ekg/EKG_027/image005.jpg",
  "/data/ekg/EKG_027/image006.jpg",
  "/data/ekg/EKG_027/image007.jpg",
  "/data/ekg/Electrolit ECG.files/image001.jpg",
  "/data/ekg/Electrolit ECG.files/image002.jpg",
  "/data/ekg/Electrolit ECG.files/image003.jpg",
  "/data/ekg/Electrolit ECG.files/image004.jpg",
  "/data/ekg/Electrolit ECG.files/image005.jpg",
  "/data/ekg/img/image001.jpg",
  "/data/ekg/img/image002.jpg",
  "/data/ekg/img/image003.jpg",
  "/data/ekg/img/image004.jpg",
  "/data/ekg/img/image005.jpg",
  "/data/ekg/img/image006.jpg",
  "/data/ekg/img/image007.jpg",
  "/data/ekg/img/image008.gif",
  "/data/ekg/img/image009.gif",
  "/data/ekg/img/image010.gif",
  "/data/ekg/img/image011.gif",
  "/data/ekg/img/image012.jpg",
  "/data/ekg/img/image013.jpg",
  "/data/ekg/img/image014.jpg",
  "/data/ekg/img/image015.png",
  "/data/ekg/img/image016.jpg",
  "/data/ekg/img/image017.gif",
  "/data/ekg/img/image018.jpg",
  "/data/ekg/img/image019.jpg",
  "/data/ekg/img/image020.gif",
  "/data/ekg/img/image021.jpg",
  "/data/ekg/img/image022.jpg",
  "/data/ekg/img/image023.gif",
  "/data/ekg/img/image024.gif",
  "/data/ekg/img/image025.gif",
  "/data/klin/Klinrec_001.html",
  "/data/klin/Klinrec_002.html",
  "/data/klin/Klinrec_003.html",
  "/data/klin/Klinrec_004.html",
  "/data/klin/Klinrec_005.html",
  "/data/klin/Klinrec_006.html",
  "/data/klin/Klinrec_007.html",
  "/data/klin/Klinrec_008.html",
  "/data/klin/Klinrec_009.html",
  "/data/klin/Klinrec_010.html",
  "/data/klin/Klinrec_011.html",
  "/data/klin/Klinrec_012.html",
  "/data/klin/Klinrec_013.html",
  "/data/klin/Klinrec_014.html",
  "/data/klin/Klinrec_015.html",
  "/data/klin/Klinrec_016.html",
  "/data/klin/Klinrec_017.html",
  "/data/klin/Klinrec_018.html",
  "/data/klin/Klinrec_019.html",
  "/data/klin/Klinrec_020.html",
  "/data/klin/Klinrec_021.html",
  "/data/klin/Klinrec_022.html",
  "/data/klin/Klinrec_023.html",
  "/data/klin/Klinrec_024.html",
  "/data/klin/Klinrec_025.html",
  "/data/klin/Klinrec_026.html",
  "/data/klin/Klinrec_027.html",
  "/data/klin/Klinrec_028.html",
  "/data/klin/Klinrec_029.html",
  "/data/klin/Klinrec_030.html",
  "/data/klin/Klinrec_031.html",
  "/data/klin/Klinrec_032.html",
  "/data/klin/Klinrec_033.html",
  "/data/klin/Klinrec_034.html",
  "/data/klin/Klinrec_035.html",
  "/data/klin/Klinrec_036.html",
  "/data/klin/Klinrec_037.html",
  "/data/klin/Klinrec_038.html",
  "/data/klin/Klinrec_039.html",
  "/data/klin/Klinrec_040.html",
  "/data/klin/Klinrec_041.html",
  "/data/klin/Klinrec_042.html",
  "/data/klin/Klinrec_043.html",
  "/data/klin/Klinrec_044.html",
  "/data/klin/Klinrec_045.html",
  "/data/klin/Klinrec_046.html",
  "/data/klin/Klinrec_047.html",
  "/data/klin/Klinrec_048.html",
  "/data/klin/Klinrec_049.html",
  "/data/klin/Klinrec_050.html",
  "/data/klin/Klinrec_051.html",
  "/data/klin/Klinrec_052.html",
  "/data/klin/Klinrec_053.html",
  "/data/klin/Klinrec_054.html",
  "/data/klin/Klinrec_055.html",
  "/data/klin/Klinrec_056.html",
  "/data/klin/Klinrec_057.html",
  "/data/klin/Klinrec_058.html",
  "/data/klin/Klinrec_059.html",
  "/data/klin/Klinrec_060.html",
  "/data/klin/Klinrec_061.html",
  "/data/klin/Klinrec_062.html",
  "/data/klin/Klinrec_063.html",
  "/data/klin/Klinrec_064.html",
  "/data/klin/Klinrec_065.html",
  "/data/klin/Klinrec_066.html",
  "/data/klin/Klinrec_067.html",
  "/data/klin/Klinrec_068.html",
  "/data/klin/Klinrec_069.html",
  "/data/klin/Klinrec_070.html",
  "/data/klin/Klinrec_071.html",
  "/data/klin/Klinrec_072.html",
  "/data/klin/Klinrec_073.html",
  "/data/klin/Klinrec_074.html",
  "/data/klin/Klinrec_075.html",
  "/data/klin/Klinrec_076.html",
  "/data/klin/Klinrec_077.html",
  "/data/klin/Klinrec_078.html",
  "/data/klin/Klinrec_079.html",
  "/data/klin/Klinrec_080.html",
  "/data/klin/Klinrec_081.html",
  "/data/klin/Klinrec_082.html",
  "/data/klin/Klinrec_083.html",
  "/data/klin/Klinrec_084.html",
  "/data/klin/Klinrec_085.html",
  "/data/klin/Klinrec_086.html",
  "/data/klin/Klinrec_087.html",
  "/data/klin/Klinrec_088.html",
  "/data/klin/Klinrec_089.html",
  "/data/klin/Klinrec_090.html",
  "/data/klin/Klinrec_091.html",
  "/data/klin/Klinrec_092.html",
  "/data/klin/Klinrec_093.html",
  "/data/klin/Klinrec_094.html",
  "/data/klin/Klinrec_095.html",
  "/data/klin/Klinrec_096.html",
  "/data/klin/Klinrec_097.html",
  "/data/klin/Klinrec_098.html",
  "/data/klin/Klinrec_099.html",
  "/data/klin/Klinrec_100.html",
  "/data/klin/Klinrec_101.html",
  "/data/klin/Klinrec_102.html",
  "/data/klin/Klinrec_103.html",
  "/data/klin/Klinrec_104.html",
  "/data/klin/Klinrec_105.html",
  "/data/klin/Klinrec_106.html",
  "/data/klin/Klinrec_107.html",
  "/data/klin/Klinrec_108.html",
  "/data/klin/Klinrec_109.html",
  "/data/klin/Klinrec_110.html",
  "/data/klin/Klinrec_111.html",
  "/data/klin/Klinrec_112.html",
  "/data/klin/Klinrec_113.html",
  "/data/klin/Klinrec_114.html",
  "/data/klin/Klinrec_115.html",
  "/data/klin/Klinrec_116.html",
  "/data/klin/Klinrec_117.html",
  "/data/klin/Klinrec_118.html",
  "/data/klin/Klinrec_119.html",
  "/data/klin/Klinrec_120.html",
  "/data/klin/Klinrec_121.html",
  "/data/klin/Klinrec_122.html",
  "/data/klin/Klinrec_123.html",
  "/data/klin/Klinrec_124.html",
  "/data/klin/Klinrec_125.html",
  "/data/klin/Klinrec_126.html",
  "/data/klin/Klinrec_127.html",
  "/data/klin/Klinrec_128.html",
  "/data/klin/Klinrec_129.html",
  "/data/klin/Klinrec_130.html",
  "/data/klin/Klinrec_131.html",
  "/data/klin/Klinrec_132.html",
  "/data/klin/Klinrec_133.html",
  "/data/klin/Klinrec_134.html",
  "/data/klin/Klinrec_135.html",
  "/data/klin/Klinrec_136.html",
  "/data/klin/Klinrec_137.html",
  "/data/klin/Klinrec_138.html",
  "/data/klin/Klinrec_139.html",
  "/data/klin/Klinrec_140.html",
  "/data/klin/Klinrec_141.html",
  "/data/klin/Klinrec_142.html",
  "/data/klin/Klinrec_143.html",
  "/data/klin/Klinrec_144.html",
  "/data/klin/Klinrec_145.html",
  "/data/klin/Klinrec_146.html",
  "/data/klin/Klinrec_147.html",
  "/data/klin/Klinrec_148.html",
  "/data/klin/Klinrec_149.html",
  "/data/klin/Klinrec_150.html",
  "/data/klin/Klinrec_151.html",
  "/data/klin/Klinrec_152.html",
  "/data/klin/Klinrec_153.html",
  "/data/klin/Klinrec_154.html",
  "/data/klin/Klinrec_155.html",
  "/data/klin/Klinrec_156.html",
  "/data/klin/Klinrec_157.html",
  "/data/klin/Klinrec_158.html",
  "/data/klin/Klinrec_159.html",
  "/data/klin/Klinrec_160.html",
  "/data/klin/Klinrec_161.html",
  "/data/klin/Klinrec_162.html",
  "/data/klin/Klinrec_163.html",
  "/data/klin/Klinrec_164.html",
  "/data/klin/Klinrec_165.html",
  "/data/klin/Klinrec_166.html",
  "/data/klin/Klinrec_167.html",
  "/data/klin/Klinrec_168.html",
  "/data/klin/Klinrec_169.html",
  "/data/klin/Klinrec_170.html",
  "/data/klin/Klinrec_171.html",
  "/data/klin/Klinrec_172.html",
  "/data/klin/Klinrec_173.html",
  "/data/klin/Klinrec_174.html",
  "/data/klin/Klinrec_175.html",
  "/data/klin/Klinrec_176.html",
  "/data/klin/Klinrec_177.html",
  "/data/klin/Klinrec_178.html",
  "/data/klin/Klinrec_179.html",
  "/data/klin/Klinrec_180.html",
  "/data/klin/Klinrec_181.html",
  "/data/klin/Klinrec_182.html",
  "/data/klin/Klinrec_183.html",
  "/data/klin/Klinrec_184.html",
  "/data/klin/Klinrec_185.html",
  "/data/klin/all_klin.json",
  "/data/klin/klin_un01.html",
  "/data/manipulation/Atlas manipul.files/image001.jpg",
  "/data/manipulation/Atlas manipul.files/image002.jpg",
  "/data/manipulation/Atlas manipul.files/image003.jpg",
  "/data/manipulation/Atlas manipul.files/image004.jpg",
  "/data/manipulation/Atlas manipul.files/image005.jpg",
  "/data/manipulation/Atlas manipul.files/image006.jpg",
  "/data/manipulation/Atlas manipul.files/image007.jpg",
  "/data/manipulation/Atlas manipul.files/image008.jpg",
  "/data/manipulation/Atlas manipul.files/image009.jpg",
  "/data/manipulation/Atlas manipul.files/image010.jpg",
  "/data/manipulation/Atlas manipul.files/image011.jpg",
  "/data/manipulation/Atlas manipul.files/image012.jpg",
  "/data/manipulation/Atlas manipul.files/image013.jpg",
  "/data/manipulation/Atlas manipul.files/image014.jpg",
  "/data/manipulation/Atlas manipul.files/image015.jpg",
  "/data/manipulation/Atlas manipul.files/image016.jpg",
  "/data/manipulation/Atlas manipul.files/image017.jpg",
  "/data/manipulation/Atlas manipul.files/image018.jpg",
  "/data/manipulation/Atlas manipul.files/image019.jpg",
  "/data/manipulation/Atlas manipul.files/image020.jpg",
  "/data/manipulation/Atlas manipul.files/image021.jpg",
  "/data/manipulation/Atlas manipul.files/image022.jpg",
  "/data/manipulation/Atlas manipul.files/image023.jpg",
  "/data/manipulation/Atlas manipul.files/image024.jpg",
  "/data/manipulation/Atlas manipul.files/image025.jpg",
  "/data/manipulation/Atlas manipul.files/image026.jpg",
  "/data/manipulation/Atlas manipul.files/image027.jpg",
  "/data/manipulation/Atlas manipul.files/image028.jpg",
  "/data/manipulation/Atlas manipul.files/image029.jpg",
  "/data/manipulation/Atlas manipul.files/image030.jpg",
  "/data/manipulation/Atlas manipul.files/image031.jpg",
  "/data/manipulation/Atlas manipul.files/image032.jpg",
  "/data/manipulation/Atlas manipul.files/image033.jpg",
  "/data/manipulation/Atlas manipul.files/image034.jpg",
  "/data/manipulation/Atlas manipul.files/image035.jpg",
  "/data/manipulation/Atlas manipul.files/image036.jpg",
  "/data/manipulation/Atlas manipul.files/image037.jpg",
  "/data/manipulation/Atlas manipul.files/image038.jpg",
  "/data/manipulation/Atlas manipul.files/image039.jpg",
  "/data/manipulation/Atlas manipul.files/image040.jpg",
  "/data/manipulation/Atlas manipul.files/image041.jpg",
  "/data/manipulation/Atlas manipul.files/image042.jpg",
  "/data/manipulation/Atlas manipul.files/image043.jpg",
  "/data/manipulation/Atlas manipul.files/image044.jpg",
  "/data/manipulation/Atlas manipul.files/image045.jpg",
  "/data/manipulation/Atlas manipul.files/image046.jpg",
  "/data/manipulation/Atlas manipul.files/image047.jpg",
  "/data/manipulation/Atlas manipul.files/image048.jpg",
  "/data/manipulation/Atlas manipul.files/image049.jpg",
  "/data/manipulation/Atlas manipul.files/image050.jpg",
  "/data/manipulation/Atlas manipul.files/image051.jpg",
  "/data/manipulation/Atlas manipul.files/image052.jpg",
  "/data/manipulation/Atlas manipul.files/image053.jpg",
  "/data/manipulation/Atlas manipul.files/image054.jpg",
  "/data/manipulation/Atlas manipul.files/image055.jpg",
  "/data/manipulation/Atlas manipul.files/image056.jpg",
  "/data/manipulation/Atlas manipul.files/image057.jpg",
  "/data/manipulation/Atlas manipul.files/image058.jpg",
  "/data/manipulation/Atlas manipul.files/image059.jpg",
  "/data/manipulation/Atlas manipul.files/image060.jpg",
  "/data/manipulation/Atlas manipul.files/image061.jpg",
  "/data/manipulation/Atlas manipul.files/image062.jpg",
  "/data/manipulation/Atlas manipul.files/image063.jpg",
  "/data/manipulation/Atlas manipul.files/image064.jpg",
  "/data/manipulation/Atlas manipul.files/image065.jpg",
  "/data/manipulation/Atlas manipul.files/image066.jpg",
  "/data/manipulation/Atlas manipul.files/image067.jpg",
  "/data/manipulation/Atlas manipul.files/image068.jpg",
  "/data/manipulation/Atlas manipul.files/image069.jpg",
  "/data/manipulation/Atlas manipul.files/image070.jpg",
  "/data/manipulation/Atlas manipul.files/image071.jpg",
  "/data/manipulation/Atlas manipul.files/image072.gif",
  "/data/manipulation/Atlas manipul.files/image073.jpg",
  "/data/manipulation/Atlas manipul.files/image074.jpg",
  "/data/manipulation/Atlas manipul.files/image075.jpg",
  "/data/manipulation/Atlas manipul.files/image076.jpg",
  "/data/manipulation/Atlas manipul.files/image077.jpg",
  "/data/manipulation/Atlas manipul.files/image078.jpg",
  "/data/manipulation/Atlas manipul.files/image079.jpg",
  "/data/manipulation/Atlas manipul.files/image080.jpg",
  "/data/manipulation/Atlas manipul.files/image081.jpg",
  "/data/manipulation/Atlas manipul.files/image082.jpg",
  "/data/manipulation/Atlas manipul.files/image083.jpg",
  "/data/manipulation/Atlas manipul.files/image084.jpg",
  "/data/manipulation/Atlas manipul.files/image085.jpg",
  "/data/manipulation/Atlas manipul.files/image086.jpg",
  "/data/manipulation/Atlas manipul.files/image087.jpg",
  "/data/manipulation/Atlas manipul.files/image088.jpg",
  "/data/manipulation/Atlas manipul.files/image089.jpg",
  "/data/manipulation/Atlas manipul.files/image090.jpg",
  "/data/manipulation/Atlas manipul.files/image091.jpg",
  "/data/manipulation/Atlas manipul.files/image092.jpg",
  "/data/manipulation/Atlas manipul.files/image093.jpg",
  "/data/manipulation/Atlas manipul.files/image094.jpg",
  "/data/manipulation/Atlas manipul.files/image095.jpg",
  "/data/manipulation/Atlas manipul.files/image096.jpg",
  "/data/manipulation/Atlas manipul.files/image097.jpg",
  "/data/manipulation/Atlas manipul.files/image098.jpg",
  "/data/manipulation/Atlas manipul.files/image099.jpg",
  "/data/manipulation/Atlas manipul_001.html",
  "/data/manipulation/Atlas manipul_002.html",
  "/data/manipulation/Atlas manipul_003.html",
  "/data/manipulation/Atlas manipul_004.html",
  "/data/manipulation/Atlas manipul_005.html",
  "/data/manipulation/Atlas manipul_006.html",
  "/data/manipulation/Atlas manipul_007.html",
  "/data/manipulation/Atlas manipul_008.html",
  "/data/manipulation/Atlas manipul_009.html",
  "/data/manipulation/Atlas manipul_010.html",
  "/data/manipulation/Atlas manipul_011.html",
  "/data/manipulation/Atlas manipul_012.html",
  "/data/manipulation/Atlas manipul_013.html",
  "/data/manipulation/Atlas manipul_014.html",
  "/data/manipulation/Atlas manipul_015.html",
  "/data/manipulation/Atlas manipul_016.html",
  "/data/manipulation/Atlas manipul_017.html",
  "/data/manipulation/Atlas manipul_018.html",
  "/data/manipulation/Atlas manipul_019.html",
  "/data/mkb/level1.json",
  "/data/mkb/level2.json",
  "/data/mkb/level3.json",
  "/data/mkb/level4.json",
  "/data/pril/Pril_001.html",
  "/data/pril/Pril_002.html",
  "/data/pril/Pril_003.html",
  "/data/pril/Pril_004.html",
  "/data/pril/Pril_005.html",
  "/data/pril/Pril_006.html",
  "/data/pril/Pril_007.html",
  "/data/pril/Pril_008.html",
  "/data/pril/Pril_009.html",
  "/data/pril/Pril_010.html",
  "/data/pril/Pril_011.html",
  "/data/pril/Pril_012.html",
  "/data/pril/Pril_013.html",
  "/data/pril/Pril_014.html",
  "/data/pril/Pril_015.html",
  "/data/pril/Pril_016.html",
  "/data/pril/Pril_017.html",
  "/data/pril/Pril_018.html",
  "/data/pril/Pril_019.html",
  "/data/pril/Pril_020.html",
  "/data/pril/Pril_021.html",
  "/data/pril/Pril_030.html",
  "/data/pril/Pril_031.html",
  "/ekg.html",
  "/empty.html",
  "/font/Open_Sans/LICENSE.txt",
  "/font/Open_Sans/OpenSans-Bold.ttf",
  "/font/Open_Sans/OpenSans-BoldItalic.ttf",
  "/font/Open_Sans/OpenSans-ExtraBold.ttf",
  "/font/Open_Sans/OpenSans-ExtraBoldItalic.ttf",
  "/font/Open_Sans/OpenSans-Italic.ttf",
  "/font/Open_Sans/OpenSans-Light.ttf",
  "/font/Open_Sans/OpenSans-LightItalic.ttf",
  "/font/Open_Sans/OpenSans-Regular.ttf",
  "/font/Open_Sans/OpenSans-SemiBold.ttf",
  "/font/Open_Sans/OpenSans-SemiBoldItalic.ttf",
  "/font/Rubik/Rubik-Black.ttf",
  "/font/Rubik/Rubik-BlackItalic.ttf",
  "/font/Rubik/Rubik-Bold.ttf",
  "/font/Rubik/Rubik-BoldItalic.ttf",
  "/font/Rubik/Rubik-Italic.ttf",
  "/font/Rubik/Rubik-Light.ttf",
  "/font/Rubik/Rubik-LightItalic.ttf",
  "/font/Rubik/Rubik-Medium.ttf",
  "/font/Rubik/Rubik-MediumItalic.ttf",
  "/font/Rubik/Rubik-Regular.ttf",
  "/font/comfortaa/Comfortaa-Bold.ttf",
  "/font/comfortaa/Comfortaa-Light.ttf",
  "/font/comfortaa/Comfortaa-Medium.ttf",
  "/font/comfortaa/Comfortaa-Regular.ttf",
  "/font/comfortaa/Comfortaa-SemiBold.ttf",
  "/img/close.svg",
  "/img/dzen.svg",
  "/img/favicons/appicon-120.png",
  "/img/favicons/appicon-180.png",
  "/img/favicons/appicon-36.png",
  "/img/favicons/appicon-48.png",
  "/img/favicons/appicon-96.png",
  "/img/localhost_3005_ (1).png",
  "/img/localhost_3005_.png",
  "/img/logo.png",
  "/img/main/contract.svg",
  "/img/main/cough.svg",
  "/img/main/gamepad.svg",
  "/img/main/gloves.svg",
  "/img/main/hand.svg",
  "/img/main/heart-rate.svg",
  "/img/main/logo_clear.svg",
  "/img/main/medical-report.svg",
  "/img/main/medical-tabk.svg",
  "/img/main/microscope.svg",
  "/img/main/mkb.svg",
  "/img/main/newspaper.svg",
  "/img/mpro.svg",
  "/img/plus.svg",
  "/img/puzzle.svg",
  "/img/rt.svg",
  "/img/search.svg",
  "/img/vk.svg",
  "/img/yt.svg",
  "/index.html",
  "/interactive.html",
  "/interactive_diff.html",
  "/js/app.js",
  "/js/framework7.min.js",
  "/js/index.js",
  "/klin_single.html",
  "/manifest.json",
  "/manipulation.html",
  "/menu/aig/aig_menu_l1.html",
  "/menu/aig/aig_menu_l10.html",
  "/menu/aig/aig_menu_l11.html",
  "/menu/aig/aig_menu_l12.html",
  "/menu/aig/aig_menu_l13.html",
  "/menu/aig/aig_menu_l14.html",
  "/menu/aig/aig_menu_l15.html",
  "/menu/algorithm_menu copy.html",
  "/menu/algorithm_menu.html",
  "/menu/atlas_derma_menu.html",
  "/menu/atlas_ekg_menu copy.html",
  "/menu/atlas_ekg_menu.html",
  "/menu/atlas_manip_menu.html",
  "/menu/klin/klin_menu.html",
  "/menu/klin/klin_menu_L1.html",
  "/menu/klin/klin_menu_L10.html",
  "/menu/klin/klin_menu_L11.html",
  "/menu/klin/klin_menu_L12.html",
  "/menu/klin/klin_menu_L13.html",
  "/menu/klin/klin_menu_L14.html",
  "/menu/klin/klin_menu_L15.html",
  "/menu/klin/klin_menu_L16.html",
  "/menu/klin/klin_menu_L17.html",
  "/menu/klin/klin_menu_L18.html",
  "/menu/klin/klin_menu_L19.html",
  "/menu/klin/klin_menu_L2.html",
  "/menu/klin/klin_menu_L20.html",
  "/menu/klin/klin_menu_L3.html",
  "/menu/klin/klin_menu_L4.html",
  "/menu/klin/klin_menu_L5.html",
  "/menu/klin/klin_menu_L6.html",
  "/menu/klin/klin_menu_L7.html",
  "/menu/klin/klin_menu_L8.html",
  "/menu/klin/klin_menu_L9.html",
  "/menu/pril_menu.html",
  "/menu/pril_menu_burn.html",
  "/menu/pril_menu_calc.html",
  "/menu/sp_submenu.html",
  "/mkb.html",
  "/mkb2.html",
  "/offline.html",
  "/other.html",
  "/pril_details.html",
  "/sw.js",
  "/text.html",
];

// 3. Установка: кэшируем все перечисленные файлы
self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS)));
});

// 4. Активация: удаляем старые версии кэша
self.addEventListener("activate", (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))));
});

// 5. Перехват запросов: сначала ищем в кэше, если нет — идём в сеть
self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;

  event.respondWith(
    caches.match(event.request, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;

      return fetch(event.request).catch(() => {
        // Сеть недоступна и файла нет в кэше
        // Для переходов между страницами (HTML) отдаём заглушку
        if (event.request.mode === "navigate" || event.request.url.includes(".html")) {
          return caches.match("/offline.html");
        }
        // Для прочих ресурсов — просто пробрасываем ошибку
        return Response.error();
      });
    })
  );
});
